#!/usr/bin/env python

import json
import textwrap
import sys

import requests

import local_fabric_settings as ls


node_info = {
    'node_name': ls.NODE_NAME,
    'node_address': ls.HOST,
}

headers = {'X-Api-Token': ls.API_TOKEN}


def print_tweet(tweet):
    print(textwrap.fill(tweet['tweet'], width=70))
    print('-')
    print('id: {}, node: {}'.format(tweet['id'], tweet['name']))
    print('='*71)


def get_tweets(local=True):
    r = requests.get('http://{}/tweets'.format(ls.HOST))

    tweets = json.loads(r.text)

    for tweet in sorted(tweets, key=lambda i: i['id'], reverse=True):
        print_tweet(tweet)


def get_tweet():
    tweet_id = input('ID of tweet to fetch: ')
    print('\n\n')

    r = requests.get('http://{}/tweets/{}'.format(ls.HOST, tweet_id))

    print_tweet(json.loads(r.text))


def post_tweet():
    tweet = input("What's on your mind: ")
    print('\n\n')

    data = json.dumps({'tweet': tweet})

    r = requests.post('http://{}/tweets'.format(ls.HOST),
                      data=data,
                      headers=headers)

    print_tweet(json.loads(r.text))


def delete_tweet():
    tweet_id = input('ID of tweet to delete: ')
    print('\n\n')

    r = requests.delete('http://{}/tweets/{}'.format(ls.HOST, tweet_id),
                        headers=headers)

    if r.status_code == 204:
        print('Tweet deleted.')
    elif r.status_code == 404:
        print('Tweet does not exist.')
    else:
        print('Something went wrong.')


ACTIONS = {
    '1': get_tweets,
    '2': get_tweet,
    '3': post_tweet,
    '4': delete_tweet,
    '100': sys.exit
}


menu = '''


SEVENTWEETS NETWORK
--------------------
Node name: {node_name}
Node address: {node_address}
--------------------

Menu:
1 - Get all local tweets
2 - Get a local tweet by id
3 - Tweet!
4 - Delete a tweet
100 - Exit

'''.format(**node_info)


if __name__ == '__main__':
    while True:
        print(menu)

        action = input('Choose action: ')
        print('\n\n')

        ACTIONS[action]()



